owner: satellitemoe
repo: upptime

sites:
  - name: Satellite Web
    url: https://satellite.moe
    icon: https://satellite.moe/favicon.ico
  - name: Satellite 24/7
    url: https://twitch.tv/satellitemoe
  - name: Satellite Chatbot
    url: $CHATBOT_URL
    icon: https://cloud.google.com/favicon.ico

status-website:
  cname: status.satellite.moe
  logoUrl: https://satellite.moe/favicon.svg
  name: Satellite Status
  navbar:
    - title: Status
      href: /
    - title: Sitio Web
      href: https://satellite.moe
    - title: 24/7
      href: https://twitch.tv/satellitemoe

i18n:
  allSystemsOperational: 🟩 Todos los sistemas funcionando
  liveStatus: Estado Actual
  overallUptime: Tiempo de Funcionamiento: $UPTIME
  overallUptimeTitle: Tiempo de Funcionamiento
  averageResponseTime: Tiempo de Respuesta Promedio: $TIMEms
  averageResponseTimeTitle: Tiempo de Respuesta Promedio
  up: Funcionando
  down: Con Problemas
  degraded: Servicio Degradado
  footer: Esta página es de [código abierto]($REPO), funciona gracias a [Upptime](https://upptime.js.org)
  
