owner: satellitemoe
repo: upptime

sites:
  - name: Satellite Web
    url: https://satellite.moe
    icon: https://satellite.moe/favicon.ico
  - name: Satellite 24/7
    url: https://twitch.tv/satellitemoe
  - name: Satellite Chatbot
    url: $CHATBOT_URL
    icon: https://cloud.google.com/favicon.ico

status-website:
  cname: status.satellite.moe
  logoUrl: https://satellite.moe/favicon.svg
  name: Satellite Status
  navbar:
    - title: Status
      href: /
    - title: Sitio Web
      href: https://satellite.moe
    - title: 24/7
      href: https://twitch.tv/satellitemoe

i18n:
  activeIncidents: Incidentes Activos
  allSystemsOperational: "Todos los sistemas funcionando"
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentViewOnGitHub: View and Subscribe on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: "← Volver a todos los incidentes"
  pastIncidents: "Incidentes Pasados"
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: "Estado Actual"
  overallUptime: "Tiempo de Funcionamiento: $UPTIME"
  overallUptimeTitle: "Tiempo de Funcionamiento"
  averageResponseTime: "Tiempo de Respuesta promedio: $TIMEms"
  averageResponseTimeTitle: "Tiempo de Respuesta Promedio"
  sevelDayResponseTime: "Tiempo de Respuesta de los últimos 7 días"
  responseTimeMs: "Tiempo de Respuesta (ms)"
  up: "Servicio Funcionando"
  down: "Servicio Caido"
  degraded: "Servicio Degradado"
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  footer: "Esta página es de [código abierto]($REPO), funciona gracias a [Upptime](https://upptime.js.org)"
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Started at
  startsAt: Starts at
  duration: "Duración"
  durationMin: "$DURATION minutos"
  incidentCompleted: Completed
  incidentScheduled: Scheduled
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: all
  locale: en-US